COMMENT ON COLUMN acs2016_5yr.geoheader.fileid IS 'Always equal to ACS Summary File identification';
COMMENT ON COLUMN acs2016_5yr.geoheader.stusab IS 'State Postal Abbreviation';
COMMENT ON COLUMN acs2016_5yr.geoheader.sumlevel IS 'Summary Level';
COMMENT ON COLUMN acs2016_5yr.geoheader.component IS 'Geographic Component';
COMMENT ON COLUMN acs2016_5yr.geoheader.logrecno IS 'Logical Record Number';
COMMENT ON COLUMN acs2016_5yr.geoheader.us IS 'US';
COMMENT ON COLUMN acs2016_5yr.geoheader.region IS 'Census Region';
COMMENT ON COLUMN acs2016_5yr.geoheader.division IS 'Census Division';
COMMENT ON COLUMN acs2016_5yr.geoheader.statece IS 'State (Census Code)';
COMMENT ON COLUMN acs2016_5yr.geoheader.state IS 'State (FIPS Code)';
COMMENT ON COLUMN acs2016_5yr.geoheader.county IS 'County of current residence';
COMMENT ON COLUMN acs2016_5yr.geoheader.cousub IS 'County Subdivision (FIPS)';
COMMENT ON COLUMN acs2016_5yr.geoheader.place IS 'Place (FIPS Code)';
COMMENT ON COLUMN acs2016_5yr.geoheader.tract IS 'Census Tract';
COMMENT ON COLUMN acs2016_5yr.geoheader.blkgrp IS 'Block Group';
COMMENT ON COLUMN acs2016_5yr.geoheader.concit IS 'Consolidated City';
COMMENT ON COLUMN acs2016_5yr.geoheader.aianhh IS 'American Indian Area/Alaska Native Area/ Hawaiian Home Land (Census)';
COMMENT ON COLUMN acs2016_5yr.geoheader.aianhhfp IS 'American Indian Area/Alaska Native Area/ Hawaiian Home Land (FIPS)';
COMMENT ON COLUMN acs2016_5yr.geoheader.aihhtli IS 'American Indian Trust Land/ Hawaiian Home Land Indicator';
COMMENT ON COLUMN acs2016_5yr.geoheader.aitsce IS 'American Indian Tribal Subdivision (Census)';
COMMENT ON COLUMN acs2016_5yr.geoheader.aits IS 'American Indian Tribal Subdivision (FIPS)';
COMMENT ON COLUMN acs2016_5yr.geoheader.anrc IS 'Alaska Native Regional Corporation (FIPS)';
COMMENT ON COLUMN acs2016_5yr.geoheader.cbsa IS 'Metropolitan and Micropolitan Statistical Area';
COMMENT ON COLUMN acs2016_5yr.geoheader.csa IS 'Combined Statistical Area';
COMMENT ON COLUMN acs2016_5yr.geoheader.metdiv IS 'Metropolitan Statistical Area-Metropolitan Division';
COMMENT ON COLUMN acs2016_5yr.geoheader.macc IS 'Metropolitan Area Central City';
COMMENT ON COLUMN acs2016_5yr.geoheader.memi IS 'Metropolitan/Micropolitan Indicator Flag';
COMMENT ON COLUMN acs2016_5yr.geoheader.necta IS 'New England City and Town Area';
COMMENT ON COLUMN acs2016_5yr.geoheader.cnecta IS 'New England City and Town Combined Statistical Area';
COMMENT ON COLUMN acs2016_5yr.geoheader.nectadiv IS 'New England City and Town Area Division';
COMMENT ON COLUMN acs2016_5yr.geoheader.ua IS 'Urban Area';
COMMENT ON COLUMN acs2016_5yr.geoheader.blank1 IS 'Reserved for future use';
COMMENT ON COLUMN acs2016_5yr.geoheader.cdcurr IS 'Current Congressional District ***';
COMMENT ON COLUMN acs2016_5yr.geoheader.sldu IS 'State Legislative District Upper';
COMMENT ON COLUMN acs2016_5yr.geoheader.sldl IS 'State Legislative District Lower';
COMMENT ON COLUMN acs2016_5yr.geoheader.blank2 IS 'Reserved for future use';
COMMENT ON COLUMN acs2016_5yr.geoheader.blank3 IS 'Reserved for future use';
COMMENT ON COLUMN acs2016_5yr.geoheader.blank4 IS 'Reserved for future use';
COMMENT ON COLUMN acs2016_5yr.geoheader.submcd IS 'Subminor Civil Division (FIPS)';
COMMENT ON COLUMN acs2016_5yr.geoheader.sdelm IS 'State-School District (Elementary)';
COMMENT ON COLUMN acs2016_5yr.geoheader.sdsec IS 'State-School District (Secondary)';
COMMENT ON COLUMN acs2016_5yr.geoheader.sduni IS 'State-School District (Unified)';
COMMENT ON COLUMN acs2016_5yr.geoheader.ur IS 'Urban/Rural';
COMMENT ON COLUMN acs2016_5yr.geoheader.pci IS 'Principal City Indicator';
COMMENT ON COLUMN acs2016_5yr.geoheader.blank5 IS 'Reserved for future use';
COMMENT ON COLUMN acs2016_5yr.geoheader.blank6 IS 'Reserved for future use';
COMMENT ON COLUMN acs2016_5yr.geoheader.puma5 IS 'Public Use Microdata Area - 5% File';
COMMENT ON COLUMN acs2016_5yr.geoheader.blank7 IS 'Reserved for future use';
COMMENT ON COLUMN acs2016_5yr.geoheader.geoid IS 'Geographic Identifier';
COMMENT ON COLUMN acs2016_5yr.geoheader.name IS 'Area Name';
COMMENT ON COLUMN acs2016_5yr.geoheader.bttr IS 'Tribal Tract';
COMMENT ON COLUMN acs2016_5yr.geoheader.btbg IS 'Tribal Block Group';
COMMENT ON COLUMN acs2016_5yr.geoheader.blank8 IS 'Reserved for future use';

